require package containing pdb
  File "/usr/share/python3.6/site-packages/_pytest/debugging.py", line 3, in <module>
    import pdb
ModuleNotFoundError: No module named 'pdb'